Drivers
sandialabs/pyscan pull request #167
Opened 2024-05-24 20:39 UTC by rsbrost

The stanford and keithley notebooks may be incomplete; however, the demo drivers test nb is sufficient for now, there are fundamentally important updates to the auto_test_driver.py file for testing drivers with read_only/write_only properties as well as to generate test logs which will be important for all drivers. This is a fairly massive update and for these reasons I suggest we go over it meticulously and pull before letting it get much larger.

2024-05-28 19:56 UTC, i-am-mounce commented on pyscan/drivers/testing/test_instrument_driver.py
remove the @property of version.

2024-05-28 19:57 UTC, i-am-mounce reviewed
Make changes suggested here and if the test_driver notebooks run, I think we can merge

2024-05-28 19:57 UTC, i-am-mounce commented on pyscan/general/get_version.py
Is this get_version of pyscan or get_version of the drivers? Be more specific.

2024-05-30 15:54 UTC, ammounce commented
Purge the test logs. Pull the version from main.

2024-06-05 16:14 UTC, i-am-mounce approved these changes

2024-06-05 16:22 UTC, i-am-mounce commented
We need tags for the conventional change log, also you have conflicts.

2024-06-05 16:22 UTC, i-am-mounce requested changes
Must have conventional change log tags and resolve conflicts.

2024-06-06 15:35 UTC, i-am-mounce approved these changes

2024-06-06 15:35 UTC, merged